version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telerag-db-gateway
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - mongo
    environment:
      APP_NAME: "MongoDB FastAPI Gateway"
      APP_VERSION: "0.0.1"
      ACCESS_USERNAME: "telerag_db"
      ACCESS_PASSWORD: "password"
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
      MONGO_USER: "root"
      MONGO_PASS: "root"
      MONGO_DB: "local"

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: me_user
      ME_CONFIG_BASICAUTH_PASSWORD: me_password
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: true
